name: Release
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
  release-github:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Package
      id: build
      run: ./build.sh

    - name: Create GitHub release
      uses: softprops/action-gh-release@v2
      with:
        files: "*.zip"
        body_path: changelog.txt
        draft: true
        fail_on_unmatched_files: true
